const bcrypt = require('bcryptjs');
const { db, T } = require('../config/database');
const {
  ACCESS_LEVELS,
  SYSTEM_ROLES,
  ROLE_NAMES,
  PERMISSION_IDS,
  DEFAULT_ROLE_PERMISSIONS,
  SUPER_ADMIN,
} = require('./permissionCatalogue');
const { BCRYPT_ROUNDS, bootstrapSuperAdmin } = require('../config/auth');

/**
 * Idempotent bootstrap of the RBAC metadata database.
 *
 * Safe to run on every start: every statement is CREATE ... IF NOT EXISTS or an
 * insert guarded by ON CONFLICT, so restarting never touches existing data.
 *
 * One deliberate difference from a conventional schema: there is no
 * `dashboards` table. In this project a dashboard IS a JSON file under
 * config/dashboards, resolved by dashboard/dashboardRegistry.js, so the
 * registry stays the single source of truth for which dashboards exist and the
 * tables here reference one only by its id. `company_dashboards` is what binds
 * a dashboard to the companies allowed to use it.
 */

const LEVEL_LIST = ACCESS_LEVELS.map((level) => `'${level}'`).join(',');

/**
 * Account lifecycle, and the reason there is no boolean `active` flag.
 *
 *   pending   created, no usable password yet, waiting on its activation link
 *   active    can sign in
 *   disabled  refused at sign-in and dropped mid-session
 *
 * "Created but not yet usable" and "switched off by an administrator" are
 * genuinely different states that need different messages and different
 * recovery paths, and a boolean forced them to share one.
 */
const USER_STATUSES = ['pending', 'active', 'disabled'];
const STATUS_LIST = USER_STATUSES.map((s) => `'${s}'`).join(',');

/*
 * Identity columns rather than SERIAL: `GENERATED BY DEFAULT AS IDENTITY` is
 * the standard spelling, owns its sequence properly, and - unlike SERIAL -
 * survives a table rename and a pg_dump round trip without leaving a stray
 * sequence behind.
 *
 * TIMESTAMPTZ rather than TIMESTAMP throughout. Every value here is an instant
 * something happened - a token issued, a session expiring, a login - and a
 * naive timestamp silently means "in whatever zone the server had at the time",
 * which is a bug waiting for a deployment to move region.
 */
const TABLES = [
  `CREATE TABLE IF NOT EXISTS ${T.companies} (
     id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name         VARCHAR(150) NOT NULL,
     slug         VARCHAR(64)  NOT NULL,
     active       BOOLEAN      NOT NULL DEFAULT TRUE,
     created_by   INTEGER      NULL,
     created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
     CONSTRAINT uq_companies_slug UNIQUE (slug),
     CONSTRAINT uq_companies_name UNIQUE (name)
   )`,

  /*
   * company_id is NULL for exactly one kind of account: a platform role, which
   * belongs to no customer company. It is enforced both ways in
   * userService.assertRoleCompanyPairing, because the database alone cannot
   * express "null if and only if the role's scope is platform".
   */
  `CREATE TABLE IF NOT EXISTS ${T.users} (
     id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     company_id           INTEGER      NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     username             VARCHAR(50)  NOT NULL,
     email                VARCHAR(190) NOT NULL,
     display_name         VARCHAR(120) NULL,
     password_hash        VARCHAR(100) NULL,
     role                 VARCHAR(50)  NOT NULL,
     status               VARCHAR(16)  NOT NULL DEFAULT 'pending',
     must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
     last_login_at        TIMESTAMPTZ  NULL,
     created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
     CONSTRAINT uq_users_username UNIQUE (username),
     CONSTRAINT uq_users_email    UNIQUE (email),
     CONSTRAINT chk_users_status  CHECK (status IN (${STATUS_LIST}))
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.roles} (
     id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name        VARCHAR(50) NOT NULL,
     scope       VARCHAR(16) NOT NULL DEFAULT 'company',
     description VARCHAR(255) NULL,
     created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
     CONSTRAINT uq_roles_name UNIQUE (name),
     CONSTRAINT chk_roles_scope CHECK (scope IN ('platform','company'))
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.rolePermissions} (
     role_name     VARCHAR(50)  NOT NULL
                     REFERENCES ${T.roles} (name) ON DELETE CASCADE ON UPDATE CASCADE,
     permission_id VARCHAR(100) NOT NULL,
     PRIMARY KEY (role_name, permission_id)
   )`,

  // Group names are unique within a company, not globally: two customers both
  // having a "Finance" group is normal and must not collide.
  `CREATE TABLE IF NOT EXISTS ${T.groups} (
     id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     company_id INTEGER      NOT NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     name       VARCHAR(100) NOT NULL,
     active     BOOLEAN      NOT NULL DEFAULT TRUE,
     creator_id INTEGER      NULL REFERENCES ${T.users} (id) ON DELETE SET NULL,
     created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
     CONSTRAINT uq_groups_company_name UNIQUE (company_id, name)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.groupUsers} (
     group_id   INTEGER     NOT NULL REFERENCES ${T.groups} (id) ON DELETE CASCADE,
     user_id    INTEGER     NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (group_id, user_id)
   )`,

  /*
   * Which dashboards a company may use at all. The platform owner writes this;
   * a company administrator can only grant what appears here for their own
   * company, so no sequence of company-level actions can reach another
   * customer's dashboard.
   *
   * dashboard_id carries no foreign key on purpose: dashboards are files.
   */
  `CREATE TABLE IF NOT EXISTS ${T.companyDashboards} (
     company_id   INTEGER     NOT NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     dashboard_id VARCHAR(64) NOT NULL,
     assigned_by  INTEGER     NULL,
     assigned_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (company_id, dashboard_id)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.dashboardAccess} (
     user_id      INTEGER     NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     dashboard_id VARCHAR(64) NOT NULL,
     access_level VARCHAR(10) NOT NULL DEFAULT 'view',
     granted_by   INTEGER     NULL,
     granted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (user_id, dashboard_id),
     CONSTRAINT chk_dashboard_access_level CHECK (access_level IN (${LEVEL_LIST}))
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.groupDashboardAccess} (
     group_id     INTEGER     NOT NULL REFERENCES ${T.groups} (id) ON DELETE CASCADE,
     dashboard_id VARCHAR(64) NOT NULL,
     access_level VARCHAR(10) NOT NULL DEFAULT 'view',
     granted_by   INTEGER     NULL,
     granted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (group_id, dashboard_id),
     CONSTRAINT chk_group_dashboard_access_level CHECK (access_level IN (${LEVEL_LIST}))
   )`,

  /*
   * Row-level scopes: which slices of DATA a user may see, as opposed to
   * dashboard_access which decides WHICH DASHBOARDS they may open.
   *
   * One row per (user, dimension, value). No rows for a dimension means
   * unrestricted on that dimension.
   *
   * STORED AND CONFIGURABLE ONLY - the query engine does not yet filter on
   * these. Enforcing them means injecting predicates in query/queryPlanner.js and
   * folding the user's scope into the cache key in query/queryCache.js, or
   * users with different scopes will read each other's cached rows.
   */
  `CREATE TABLE IF NOT EXISTS ${T.userDataScope} (
     user_id    INTEGER      NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     dimension  VARCHAR(64)  NOT NULL,
     value      VARCHAR(120) NOT NULL,
     created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
     PRIMARY KEY (user_id, dimension, value)
   )`,

  /*
   * Refresh sessions, one row per issued token.
   *
   * `family_id` ties every token in one login chain together. Rotation writes a
   * new row in the same family and marks the old one replaced; presenting a
   * replaced token means it leaked, so the whole family is revoked at once
   * rather than just the one row - see auth/tokenService.js.
   *
   * Only the HMAC of the token is stored. A dump of this table cannot be
   * replayed without JWT_REFRESH_SECRET, which lives outside the database.
   */
  `CREATE TABLE IF NOT EXISTS ${T.refreshTokens} (
     id             UUID        PRIMARY KEY,
     family_id      UUID        NOT NULL,
     user_id        INTEGER     NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     token_hash     CHAR(64)    NOT NULL,
     issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
     expires_at     TIMESTAMPTZ NOT NULL,
     revoked_at     TIMESTAMPTZ NULL,
     revoked_reason VARCHAR(40) NULL,
     replaced_by    UUID        NULL,
     CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
   )`,

  /*
   * Single-use links sent by email. Currently one purpose - activation, which
   * covers both first onboarding and an administrator reissuing access - but
   * the column is there so a second purpose needs no migration.
   */
  `CREATE TABLE IF NOT EXISTS ${T.userTokens} (
     id          UUID        PRIMARY KEY,
     user_id     INTEGER     NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     purpose     VARCHAR(24) NOT NULL,
     token_hash  CHAR(64)    NOT NULL,
     expires_at  TIMESTAMPTZ NOT NULL,
     consumed_at TIMESTAMPTZ NULL,
     created_by  INTEGER     NULL,
     created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
     CONSTRAINT uq_user_tokens_hash UNIQUE (token_hash)
   )`,

  /*
   * Login throttling state, keyed by the identifier that was typed rather than
   * by IP: the thing being protected is one account's password, and an IP is
   * cheap to change. Rows for identifiers that name no account are kept too, so
   * the table cannot be used to tell which usernames exist.
   */
  `CREATE TABLE IF NOT EXISTS ${T.loginAttempts} (
     identifier        VARCHAR(190) PRIMARY KEY,
     attempts          INTEGER      NOT NULL DEFAULT 0,
     window_started_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
     locked_until      TIMESTAMPTZ  NULL
   )`,
];

/*
 * Secondary indexes. Separate statements because PostgreSQL declares indexes
 * outside CREATE TABLE - only PRIMARY KEY and UNIQUE live inline - and because
 * CREATE INDEX IF NOT EXISTS makes each one independently idempotent.
 */
const INDEXES = [
  `CREATE INDEX IF NOT EXISTS idx_users_company ON ${T.users} (company_id)`,
  `CREATE INDEX IF NOT EXISTS idx_groups_creator ON ${T.groups} (creator_id)`,
  `CREATE INDEX IF NOT EXISTS idx_group_users_user ON ${T.groupUsers} (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_company_dashboards_dashboard ON ${T.companyDashboards} (dashboard_id)`,
  `CREATE INDEX IF NOT EXISTS idx_dashboard_access_dashboard ON ${T.dashboardAccess} (dashboard_id)`,
  `CREATE INDEX IF NOT EXISTS idx_group_dashboard_access_dashboard ON ${T.groupDashboardAccess} (dashboard_id)`,
  `CREATE INDEX IF NOT EXISTS idx_user_data_scope_user ON ${T.userDataScope} (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family ON ${T.refreshTokens} (family_id)`,
  `CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON ${T.refreshTokens} (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expiry ON ${T.refreshTokens} (expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_user_tokens_user ON ${T.userTokens} (user_id, purpose)`,
];

let ready = false;
let readyError = null;

/** True once bootstrap has succeeded. The API answers 503 until it has. */
function isRbacReady() {
  return ready;
}

/** Why bootstrap failed, for the health endpoint. Null while it has not. */
function rbacError() {
  return readyError;
}

async function seedRoles() {
  // Tracks which roles this start created, so defaults are seeded exactly once
  // in the role's lifetime rather than whenever the role happens to be empty.
  const created = new Set();

  for (const role of SYSTEM_ROLES) {
    const { rows } = await db.query(
      `INSERT INTO ${T.roles} (name, scope, description) VALUES (?, ?, ?)
       ON CONFLICT (name) DO UPDATE SET scope = EXCLUDED.scope, description = EXCLUDED.description
       RETURNING (xmax = 0) AS inserted`,
      [role.name, role.scope, role.description]
    );
    // xmax is 0 on a freshly inserted row and non-zero on one the conflict
    // clause updated - the standard way to tell an upsert's two outcomes apart.
    if (rows[0] && rows[0].inserted) created.add(role.name);
  }

  /*
   * Defaults are seeded only for a role this start actually created.
   *
   * Seeding whenever a role holds no permissions reads as the same thing but is
   * not: an administrator who deliberately strips a role back to nothing would
   * have the defaults restored under them at the next restart, silently
   * re-granting what they had just removed.
   */
  for (const [roleName, permissions] of Object.entries(DEFAULT_ROLE_PERMISSIONS)) {
    if (!created.has(roleName)) continue;
    for (const permissionId of permissions) {
      await db.query(
        `INSERT INTO ${T.rolePermissions} (role_name, permission_id) VALUES (?, ?)
         ON CONFLICT DO NOTHING`,
        [roleName, permissionId]
      );
    }
    console.log(`[rbac] seeded ${permissions.length} default permissions for ${roleName}`);
  }

  // A permission retired from the catalogue would still be handed to `can`,
  // which throws on an unknown id. Dropping it here keeps the table and the
  // catalogue in step.
  const purged = await db.query(
    `DELETE FROM ${T.rolePermissions}
      WHERE permission_id NOT IN (${PERMISSION_IDS.map(() => '?').join(',')})`,
    PERMISSION_IDS
  );
  if (purged.rowCount) {
    console.log(`[rbac] removed ${purged.rowCount} permission row(s) no longer in the catalogue`);
  }

  /*
   * A role outside the three-role model would still resolve to permissions and
   * still be assignable. Removing it is safe only once nothing holds it, so the
   * users table is checked first and a role with holders is an error rather
   * than a silent deletion that would strand those accounts.
   */
  const stale = await db.query(
    `SELECT name FROM ${T.roles} WHERE name NOT IN (${ROLE_NAMES.map(() => '?').join(',')})`,
    ROLE_NAMES
  );
  for (const row of stale.rows) {
    const held = await db.query(`SELECT COUNT(*)::int AS n FROM ${T.users} WHERE role = ?`, [row.name]);
    if (held.rows[0].n > 0) {
      throw new Error(
        `Role "${row.name}" is not part of the three-role model but ${held.rows[0].n} account(s) still hold it. ` +
        `Reassign them to one of ${ROLE_NAMES.join(', ')} before starting the server.`
      );
    }
    await db.query(`DELETE FROM ${T.roles} WHERE name = ?`, [row.name]);
    console.log(`[rbac] removed unused role "${row.name}"`);
  }
}

async function seedSuperAdmin() {
  const { rows } = await db.query(`SELECT COUNT(*)::int AS n FROM ${T.users}`);
  if (rows[0].n > 0) return false;

  // Read only when it is actually needed: an installation that already has
  // users must not be held to having the bootstrap variables still set.
  const { username, email, password } = bootstrapSuperAdmin();
  const hash = bcrypt.hashSync(String(password), BCRYPT_ROUNDS);

  await db.query(
    `INSERT INTO ${T.users} (company_id, username, email, password_hash, role, status, must_change_password)
     VALUES (NULL, ?, ?, ?, ?, 'active', TRUE)`,
    [username, String(email).toLowerCase(), hash, SUPER_ADMIN]
  );
  console.log(
    `[rbac] seeded platform owner "${username}" as ${SUPER_ADMIN}, ` +
    'flagged to change its password at first sign-in'
  );
  return true;
}

/**
 * Creates the database, tables, indexes and seed rows when they are missing.
 * Resolves once the RBAC layer is usable.
 */
async function bootstrapAppMeta() {
  try {
    for (const ddl of TABLES) await db.raw(ddl);
    for (const ddl of INDEXES) await db.raw(ddl);

    await seedRoles();
    await seedSuperAdmin();

    ready = true;
    readyError = null;
    return true;
  } catch (err) {
    ready = false;
    readyError = err.message;
    throw err;
  }
}

module.exports = { bootstrapAppMeta, isRbacReady, rbacError, USER_STATUSES, TABLES, INDEXES };
